services:
  online-store-app:
    build: .
    container_name: online-store-app
    environment:
      DB_HOST: postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - store-app-network


  postgres:
    image: postgres
    container_name: db-app
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - db-app:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - store-app-network


volumes:
  db-app:

networks:
  store-app-network:
    driver: bridge